### ISSUE TITLE
Provide an example on how to use this on the command line

### ISSUE THREAD

**Issue by trajano** [futurGH/ts-to-jsdoc#1]
It would be nice to do one off ts to jsdoc conversions, can you provide an example on how to do this via the command line

I was hoping for something lie

npx ts-to-jsdoc filename.ts

**Comment by futurGH** [comment]
It is currently possible to generate JSDoc via the command line using my [ts-docmagen](https://github.com/futurGH/ts-docmagen) package that depends on this with the `--no-purge-temp` and `--no-docs` flags.

However, I realize that isn't entirely intuitive and could definitely be implemented in this package as a standalone feature as well. This is something I will be looking into in the near future; thanks for your attention!
