### ISSUE TITLE
For a single input .ts file, imports in the .ts file cause an error, which does indicate what to do

### ISSUE THREAD

**Issue by FranzZemen** [futurGH/ts-to-jsdoc#14]
Not a showstopper, but would be helpful for new users.

Use case:  I was generating .js file from a single .ts file.  It failed with an ambiguous error.  The file had imports, and I presumed that was the issue.  The directory was self-containing i.e. .ts in this directory only imported from themselves or from node.  So I used the directory option and that worked.

Fix  suggested:  

- Provide a more intuitive error message
- or Convert imports as well (or handle in some way)

**Comment by futurGH** [comment]
Definitely worth supporting imports, I think it makes more sense to track this on #15.
