### ISSUE TITLE
Not generating imports for externally defined typedefs

### ISSUE THREAD

**Issue by FranzZemen** [futurGH/ts-to-jsdoc#15]
typedefs were properly generated from a source file.  Another .ts source refers to those types, and to make it work I had to add typedefs to import those in the target .js

For example:

/**
 * @typedef {import('./log-interface').TreatmentName} TreatmentName
 */

**Comment by futurGH** [comment]
Currently, ts-to-jsdoc individually transpiles each file. In addition to not supporting imports, this is probably much slower overall than handling transpilation on a project level. I'd like to make that change eventually, but it's going to take some time & effort. I'd be happy to accept any PRs working towards that in the meantime.

**Comment by FranzZemen** [comment]
I'll start looking at the code base and get familiar with it.  I like where this project is going, I didn't find anything like it.  I found it useful to help me with some shims that I was working on.
