### ISSUE TITLE
Arrow functions are not supported

### ISSUE THREAD

**Issue by weakish** [futurGH/ts-to-jsdoc#17]
Type info of parameters of arrow functions are stripped.

```ts
type Video = {
  id: string;
  // more fields
};

type Playlist = {
  videos: Video[];
};

const fetchPlaylist = async (
  playlistId: string,
): Promise<Playlist> => {
  // some code
};
```

will just be converted to

```js
const fetchPlaylist = async (playlistId) => { /* code */}
```

However, if refactor fetchPlaylist to `async function fetchPlaylist()`, 
ts-to-jsdoc will convert type infos to JSDoc successfully.

**Comment by futurGH** [comment]
Resolved by #24
