### ISSUE TITLE
Is it possible to take `.d.ts` + `.js` to output -> JSDoc-style `.js`?

### ISSUE THREAD

**Issue by matthew-dean** [futurGH/ts-to-jsdoc#18]
I assume this tool can't do this, but I'm wondering if you might know how to go about it.

For instance, I'm looking at a repo that has each `.js` file documented with a `.d.ts` file, which I'd like to merge.

**Comment by futurGH** [comment]
Doing that would be fairly different from how ts-to-jsdoc works. The library used internally, ts-morph, _should_ be able to read & parse .d.ts source files (but don't quote me on that) — I'm not sure how you'd translate a symbol between them and JS files though. 

It's worth checking if ts-morph can handle .js/.d.ts projects with allowJs in the configuration, but if it can't, your best bet would probably be parsing out comments with ts-morph and using something like https://github.com/acornjs/acorn to write them to the corresponding JS files.
