### ISSUE TITLE
use strict: not found

### ISSUE THREAD

**Issue by S222em** [futurGH/ts-to-jsdoc#3]
```shell
/var/Discord/gcomponents/node_modules/.bin/ts-to-jsdoc: 1: use strict: not found
: not foundd/gcomponents/node_modules/.bin/ts-to-jsdoc: 1:
/var/Discord/gcomponents/node_modules/.bin/ts-to-jsdoc: 2: Syntax error: "(" unexpected
```

**System: Windows Linux Subsystem Ubuntu**

**Comment by Mcsavvy** [comment]
I had this same issue too, I thought it was a bug in the script but it's just that it's being executed as a shell script.

Add `#!/usr/bin/env node` as the first line in the file.
To get the path to the file do `whereis ts-to-jsdoc`

**Comment by S222em** [comment]
> I had this same issue too, I thought it was a bug in the script but it's just that it's being executed as a shell script.
> 
> 
> 
> Add `#!/usr/bin/env node` as the first line in the file.
> 
> To get the path to the file do `whereis ts-to-jsdoc`

Weird thing is, that does not work for me. The path does not exist even tho im pretty sure it does. But I will try again.

**Comment by Mcsavvy** [comment]
Post the error you are getting.

**Comment by futurGH** [comment]
Sorry about that! I forgot to test the previous version in a Linux environment. Mind trying out ts-to-jsdoc@1.1.2 and letting me know if that works?
