### ISSUE TITLE
Missing param when using default value

### ISSUE THREAD

**Issue by kungfooman** [futurGH/ts-to-jsdoc#34]
Hey! I tested it on itself and this is a mistake in transpilation process:

![image](https://github.com/futurGH/ts-to-jsdoc/assets/5236548/aefbeb8a-c325-4c84-b37e-55152a3057b6)

(it drops the `@param` including the description)

Another case:

![image](https://github.com/futurGH/ts-to-jsdoc/assets/5236548/f3877fb0-5811-4fa0-8797-9c1fcccc1c83)

(missing `filename` and `debug`)

**Comment by futurGH** [comment]
Thanks!

**Comment by kungfooman** [comment]
Thank you for the quick fixing + unit test!
