### ISSUE TITLE
File content replaced with that of imported file when transpiling single file

### ISSUE THREAD

**Issue by MrNaceja** [futurGH/ts-to-jsdoc#42]
When in a typescript file I use "import" to import an external type (from another ts file) the result generated is an ""export {}".
![Captura de tela 2024-04-14 193034](https://github.com/futurGH/ts-to-jsdoc/assets/71296941/fcc73eb3-fcc5-4334-a64a-baaf37d93df5)

**Comment by futurGH** [comment]
Fixed in 2.1.1!
