### ISSUE TITLE
the tool does nothing

### ISSUE THREAD

**Issue by andremarcondesteixeira** [futurGH/ts-to-jsdoc#44]
When try to use it, it does not output anything

OS: Windows 11
Node: 20.16.0
NPM: 10.8.1

Steps to reproduce:
1. Create a new ts project
2. try to transpile it

Expected result: 
get vanilla js files

Actual result:
no output

**Comment by futurGH** [comment]
Can you share the project you're trying to transpile and how you're running ts-to-jsdoc?
