### ISSUE TITLE
Open to making it work in the browser?

### ISSUE THREAD

**Issue by smacpherson64** [futurGH/ts-to-jsdoc#45]
First off, this is incredible. Thank you so much for the hard work put into this!

I have made a quick browser prototype that allows users to generate the types in the browser. https://smacpherson64.github.io/typescript-to-jsdoc/

I would love to use `ts-to-jsdoc` directly, but had to make two adjustments to get it to work in the browser: 
- Add the config option `useInMemoryFileSystem: true` to the project
- Remove the node 'path' dependency

Would you be open to a PR to add a browser based version alongside the node one?

**Comment by kungfooman** [comment]
Can't you just add an import map entry for `path` that acts like a polyfill?

**Comment by smacpherson64** [comment]
Hi @kungfooman, thanks for the response!

Yes, an import map will likely work for the node path issue.

My main thought with a separate in memory endpoint is to stay up to date with dependencies. For an in memory version, the path dependency isn't necessary since the provided code should be the only file in the project. 

All this being said, I will move towards the import map with the prototype. Looking back through the commits, the node dependencies seem stable.

Would you be open to changes around the config option?

Thanks again for the response and your time!

**Comment by futurGH** [comment]
For sure, feel free to open a PR!

**Comment by smacpherson64** [comment]
Hey @futurGH and @kungfooman,

Thank you so much for the responses and being open to this idea.

Here are two PRs that move towards using `ts-to-jsdoc` directly in the browser:

1. Most ideal path for browser (no need to polyfill path): 
https://github.com/futurGH/ts-to-jsdoc/pull/46

2. Alternative to make the smallest possible change: 
https://github.com/futurGH/ts-to-jsdoc/pull/47

Both options pass the tests locally. Are there any other steps for testing and verification to make sure it is working as desired?

Thanks again for the opportunity!
