### ISSUE TITLE
Online playground

### ISSUE THREAD

**Issue by Lehoczky** [futurGH/ts-to-jsdoc#50]
Hey There 👋 

I've seen @smacpherson64 created an online playground at [typescript-to-jsdoc](https://github.com/smacpherson64/typescript-to-jsdoc ) and it really helps understanding what the library does, and allows us the check out what the generated jsdoc looks like.

What do you think about linking it in the README, or directly adding it to the repo (if @smacpherson64 is okay with it)? It could be even used later for bug reproductions by adding a code sharing functionality to it, like what https://www.typescriptlang.org/play/ has.

**Comment by kungfooman** [comment]
Good idea, we could also use a dedicated website... everything costs money and time of course, so a few donations to show support would be nice.

Direct link: https://smacpherson64.github.io/typescript-to-jsdoc/

I would also prefer Monaco Diff: [ts-to-jsdoc Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.50.0#XQAAAAKbAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2G81RgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTwo3x9G8PT6RMWnK8AOmAVCBigwqm_uuRNk9Vfzn8tjboVWwtudakvNcMds5I1G57yV9E_saGRYDmmUnBeck0E8yx1Zt4KknB3Rh7P8bHg1IcvQUdWpxbYqOvu1YGQTwkrK28ovKZD2sU5yrt9Ee6f9pk6iKJFYzmeqwwyc4udp09iVtJq93oUCmkLZ_eRrKkwRfvAMhsHCFp0qm5J37_hCjm527CddVD_1mh_XXHchhEZ4Et0yQW2G0HhRV4EpB4oJKtHzZ5N-SaOeLJiG2Nptvf-1eBTAebsy-sLEgDQdP_STnty)

**Comment by smacpherson64** [comment]
Absolutely, please feel free to use the code or the site in any way.

**Comment by futurGH** [comment]
For sure! This is a great tool, thanks @smacpherson64!
