### ISSUE TITLE
Ability to add `*.js` file extension to relative imports

### ISSUE THREAD

**Issue by kungfooman** [futurGH/ts-to-jsdoc#55]
I would like to directly use the output of `ts-to-jsdoc` in ESM `<script type="module">` HTML files and one flaw that still exists is the lack of "proper" filenames:

![image](https://github.com/user-attachments/assets/21248993-cc3d-4d23-a7e2-5d886070ae8f)

It would be amazing to generate proper file names by default, or at least make it an option to reduce the amount of braindead work that we have to do. Any thoughts?

**Comment by futurGH** [comment]
I don't think this is within scope for this library. The recommendation should be the same as that of the TS maintainers — write your imports the way you want them to appear in your output.
