### ISSUE TITLE
Type predicates not working correctly

### ISSUE THREAD

**Issue by timonson** [futurGH/ts-to-jsdoc#7]
Hi,

this is a very useful project!

Unfortunately [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) are not converted correctly. They are just converted to `@return {boolean}`.
Would this be inside the *purpose* of `ts-to-jsdoc`?

Thank you!

**Comment by futurGH** [comment]
I don't believe JSDoc [supports more detailed return type annotations than that?](https://jsdoc.app/tags-returns.html) If I'm wrong on that, that's definitely something I'd look to implement.

**Comment by timonson** [comment]
Thank you! I wasn't sure if TypeScript types would be converted according to this [documentation](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html).

**Comment by pfgithub** [comment]
Typescript seems to support type guards in jsdoc comments

```ts
// @ts-check

/**
 * @param {unknown} a 
 * @returns {a is string}
 */
function testGuard(a) {
    return typeof a === "string";
}

/**
 * @param {unknown} v 
 */
function demo(v) {
    if(testGuard(v)) {
        v.includes("test");
    }
    // @ts-expect-error
    v.includes("test");
}
```

**Comment by timonson** [comment]
Yes exactly, but the JsDoc documentation you linked to doesn't. The reason why I opened this issue is that I knew TS supports these types in JsDoc.

**Comment by futurGH** [comment]
Hm. My original intention for this project was to convert TypeScript code into a format that can be used by documentation generators and the like not aware of TypeScript. I'd assume, though TypeScript itself accepts this syntax in checking JS, not many other tools would.

I'm curious, though — what's the use case for using TS to check code that's been transpiled to JS? I'd be willing to look at a PR that implemented this if I can better understand how it would be used.

**Comment by timonson** [comment]
That's a great question! I would like to quote something from the [deno website](https://deno.com/blog/v1.21#deno-check-and-the-path-to-not-type-checking-by-default) to answer it.

> The last few years have shown how tremendously useful it is to be able to annotate JavaScript code with type information (usually in the form of TypeScript). This has two primary benefits:

> - Type information helps generate documentation automatically, both in the form of IDE hints / completions, and in the form of static documentation pages like on https://doc.deno.land/.
> - Type information can be used to verify that a given bit of code is semantically correct (type check).

> Both of these benefits are very useful, but at different times. The first is an ambient benefit that is always useful during development. The second is a more sophisticated benefit that is only useful just before you are going to ship some code. The type checker is really just a very very powerful linter that can help you discover problems in your code before you run it.

> Additionally, with [JavaScript being on the path to get type annotations natively](https://github.com/tc39/proposal-type-annotations), the semantics browsers will use when they encounter type comments will be unlike Deno. They will not type check before running some code, instead leaving that step to a separate type checking step that developers run before shipping the code.

I converted my web components framework [shadow](https://github.com/Zaubrik/shadow) from TypeScript to JavaScript (with JSDoc) to utilize the mentioned advantages and to avoid the frequent transpiling step from TS to JS. `ts-to-jsdoc` helped me a lot doing that, thank you!

**Comment by futurGH** [comment]
Thanks for the references @timonson @pfgithub. Given that `x is type` syntax is really only supported by TypeScript, in my mind it would be a bit strange for a tool whose purpose is to translate TypeScript syntax to a more general one to opt for that syntax by default. 

If there's other JSDoc syntax like this, or if someone's willing to put in the effort for a PR, a "typescript" mode option that uses TS-specific syntax might be a good idea, but I think it would be detrimental to the purpose of this tool for it to consider TS syntax the default.
