### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ScreamZ** [futurGH/ts-to-jsdoc#8]
Just wanted to thank you, i can now say fuck to any anti-typescript people without problems and really quickly. Ima write an article on that ahahah

**Comment by liorGameDev** [comment]
I would like to say Thank you as well for the idea.
Can you pls add an example of how to use it with loading a file and not just a string? Or how to generate a whole .ts project with it? @futurGH

**Comment by ScreamZ** [comment]
`npx ts-to-jsdoc <path to fodler or file>` you can also use `--o` to specify target folder of compiled file. Take care doesn't work well with `.tsx` files.

**Comment by futurGH** [comment]
> I would like to say Thank you as well for the idea.
> Can you pls add an example of how to use it with loading a file and not just a string? Or how to generate a whole .ts project with it? @futurGH

You can call `ts-to-jsdoc` directly from the command line if you have the package installed, passing it a file or directory path. See the "Command Line" example in the README for documentation on flags & options you can use.
