### ISSUE TITLE
use git to track transformed files

### ISSUE THREAD

**Issue by milahu** [futurGH/ts-to-jsdoc#9]
i have a similar script to remove typescript types, and generate pretty javascript
https://github.com/milahu/random/blob/master/javascript/tsx2jsx.mjs

that script will run 2 loops

1. rename files from *.ts to *.js
2. transform all files from step 1

inspect the transform: `git diff HEAD^`
revert the transform: `git reset --hard HEAD~2`

this could be hidden behind a flag like `ts-to-jsdoc --git`

**Comment by futurGH** [comment]
Like I mentioned on #10, I want to avoid expanding the surface area of this project without compelling reasoning & support for a feature from a number of users.
